### ISSUE TITLE
DFD0

### ISSUE THREAD

**Issue by aaan-gelina** [aaan-gelina/ChatterBox#37]
You will need to model and analyze your use cases and requirements properly using the appropriate models with the appropriate level of granularity.  For the projects, at a minimum,  you will need to ensure that you have the appropriate sequence diagrams (supporting your use cases), as well as DFDs (you will need to have at least a level 0 and level 1).

**Comment by gretaLiesch** [comment]
Broken down into small issues:
-find external actors
-find external data stores
-find information flows between system and outside actors
