### ISSUE TITLE
DFD1

### ISSUE THREAD

**Issue by aaan-gelina** [aaan-gelina/ChatterBox#38]
You will need to model and analyze your use cases and requirements properly using the appropriate models with the appropriate level of granularity.  For the projects, at a minimum,  you will need to ensure that you have the appropriate sequence diagrams (supporting your use cases), as well as DFDs (you will need to have at least a level 0 and level 1).

**Comment by gretaLiesch** [comment]
Broken down into smaller issues:
-find processes within the system
-find information flows within the system
-find the system boundary
-find data store accesses during data flows
